# Generated by Django 5.2.3 on 2025-06-19 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CVEEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve', models.CharField(max_length=30)),
                ('title', models.TextField()),
                ('cvss', models.CharField(max_length=10)),
                ('base_severity', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('epss', models.CharField(max_length=10)),
                ('product', models.CharField(max_length=100)),
            ],
        ),
    ]
