# Generated by Django 5.2.3 on 2025-06-19 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cveentry',
            name='product',
        ),
        migrations.AddField(
            model_name='cveentry',
            name='cwe',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cveentry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cveentry',
            name='editeur',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cveentry',
            name='lien',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cveentry',
            name='percentile',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cveentry',
            name='produit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cveentry',
            name='versions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cveentry',
            name='base_severity',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='cveentry',
            name='cve',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='cveentry',
            name='cvss',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cveentry',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cveentry',
            name='epss',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
