# Generated by Django 4.2.23 on 2025-06-19 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_subscription_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='severity',
        ),
    ]
