# Generated by Django 4.2.23 on 2025-06-19 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_subscription_severity'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('cve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cveentry')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.subscription')),
            ],
            options={
                'unique_together': {('subscription', 'cve')},
            },
        ),
    ]
